name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }] # обновление каждый час
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          config_timezone: Europe/Moscow
          plugin_languages: yes
          plugin_followup: yes
          plugin_stargazers: yes


  
